config/routes.rb
Rails.application.routes.draw do
  root  'posts#index'  
  resources :posts, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new 
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    content = @post.content
    marcov = content.split(/\n|\r|\s|。|、/)
    splitmarkov = marcov.shuffle
    @post.content = splitmarkov.join
  end
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end


private
  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markov</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="header__title">
      </div>
      <div class="header__right">
          <%= link_to "TOP", '/', class: "header__right--btn" %>
          <%= link_to "新規投稿", new_post_path, class: "header__right--btn" %>
      </div>
    </div>
    <div class="contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
  <div class="content">
    <div class="content__left">
      <%# <div class="content__left--image"></div> %>
    </div>
    <div class="content__right">
      <div class="content__right__top">
        <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %>
      </div>
      <div class="content__right__top">
        <%= link_to "❌", post_path(post.id), method: :delete %>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render partial: "post", locals: { post: post } %>
<% end %>

app/views/posts/new.html.erb
<div class="content__title">
  新規記事の作成
</div>

<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :本文, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/show.html.erb
<div class="postTitle">
  <%= @post.title %>
</div>
<div class="postDate">
  <%= @post.created_at %>
</div>
  <div class="postManage">
  </div>
<div class="postText">
  <%= simple_format @post.content %>
</div>